version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - '3000:80'
